FROM php:7.3-apache
RUN apt-get update
RUN docker-php-ext-install pdo pdo_mysql mysqli
RUN a2enmod rewrite
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY . /home/app
WORKDIR /home/app

CMD php artisan serve --host=0.0.0.0 --port=8000
EXPOSE 8000
